name: Main
on: [push]
env:
  NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://nuget.pkg.github.com/AuxLabs/index.json
    - name: Publish
      run: dotnet publish -c Release
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: "/home/runner/work/TwitchScopinator/TwitchScopinator/src/TwitchScopinator/bin/Release/net7.0/wwwroot"
        SINGLE_COMMIT: true
