name: Main
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://nuget.pkg.github.com/AuxLabs/index.json
    - name: Publish
      run: dotnet publish -c Release -o release --nologo
    - name: Set Base Tag
      run: sed -i 's/<base href="\/" \/>/<base href="\/TwitchScopinator\/" \/>/g' release/wwwroot/index.html
    - name: Copy index to 404
      run: cp release/wwwroot/index.html release/wwwroot/404.html
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
